# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='tweet',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
    ]
